services:
  kernel.listener.swagger.view:
    class: KleijnWeb\SwaggerBundle\EventListener\ViewListener
    arguments: ['@swagger.response.factory']
    tags:
      - { name: kernel.event_listener, event: kernel.view, method: onKernelView }
    public: true

  kernel.listener.swagger.exception:
    class: KleijnWeb\SwaggerBundle\EventListener\ExceptionListener
    arguments: ['@swagger.response.error_response_factory.simple', '@swagger.response.error.logref_builder', '@logger']
    tags:
      - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
    public: true

  kernel.listener.swagger.request:
    class: KleijnWeb\SwaggerBundle\EventListener\RequestListener
    arguments: [ '@swagger.request.processor']
    tags:
      - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
    public: true